<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Supported Countries (Scraper)
    |--------------------------------------------------------------------------
    | Used for the country dropdown on the scraper form.
    */
    'list' => [
        'Afghanistan',
        'Australia',
        'Austria',
        'Bahrain',
        'Bangladesh',
        'Belgium',
        'Brazil',
        'Canada',
        'China',
        'Denmark',
        'Egypt',
        'Finland',
        'France',
        'Germany',
        'Greece',
        'Hong Kong',
        'India',
        'Indonesia',
        'Iran',
        'Iraq',
        'Ireland',
        'Italy',
        'Japan',
        'Jordan',
        'Kenya',
        'Kuwait',
        'Malaysia',
        'Mexico',
        'Netherlands',
        'New Zealand',
        'Nigeria',
        'Norway',
        'Oman',
        'Pakistan',
        'Philippines',
        'Poland',
        'Qatar',
        'Russia',
        'Saudi Arabia',
        'Singapore',
        'South Africa',
        'South Korea',
        'Spain',
        'Sri Lanka',
        'Sweden',
        'Switzerland',
        'Thailand',
        'Turkey',
        'United Arab Emirates',
        'United Kingdom',
        'United States',
        'Vietnam',
    ],
];
